/** @format */

export const templatePage = {
  breadcrumbTemplate: '[class="el-breadcrumb__inner"] [href="#/content/templates"]',
  templateBanner: ".size-header",
  templateBannerTab: "#tab-banner",
  templateItems: "#size-presets .size-card",
  templateTitleField: '[placeholder="Untitled Template"]',
  createTemplateBtn: '[data-cy="createTemplate"]',
  createRectangle: '[data-cy="createRectangle"]',
  createCircle: '[data-cy="createCircle"]',
  createText: '[data-cy="createTextbox"]',
  strokeCheckbox: '[data-cy="strokeCheckbox"]',
  shadowCheckbox: '[data-cy="shadowCheckbox"]',
  layer: '[data-cy="layerLabel"]',
  horizontalAlign: "#align-center-horizontal > #small-rectangle",
  verticalAlign: "#align-center-vertical > #small-rectangle",
  strokeCheckbox: '[data-cy="strokeCheckbox"]',
  publishTemplate: "#publish-template-toggle",
  confirmPublish: ".el-dialog > .el-dialog__footer > .dialog-footer > .el-button--primary",
  templateCard: (title) => `[data-cy="templateCard"] [title=${title}]`,
  templateWidth: '[placeholder="Width"]',
  templateHeight: '[placeholder="Height"]',
  colorFillPick: '[data-cy="fillFillPickerInputHex"]',
  dragItem: '[data-cy="contentItem"]',
  canvas: '[data-cy="canvas"]',
};
