/** @format */

export const templatePage = {
  templateBanner: ".size-header",
  templateBannerTab: "#tab-banner",
  templateItems: "#size-presets .size-card",
  templateTitleField: '[placeholder="Untitled Template"]',
  createTemplateBtn: '[data-cy="createTemplate"]',
  exitTemplateBtn: ".sidebar-footer > div > .el-button--default",
  createRectangle: '[data-cy="createRectangle"]',
  createCircle: '[data-cy="createCircle"]',
  createText: '[data-cy="createTextbox"]',
  layer: '[data-cy="layerLabel"]',
  horizontalAlign: "#align-center-horizontal > #small-rectangle",
  verticalAlign: "#align-center-vertical > #small-rectangle",
  strokeCheckbox: '[data-cy="strokeCheckbox"]',
  shadowCheckbox: '[data-cy="shadowCheckbox"]',
  publishTemplate: "#publish-template-toggle",
  editTemplate: '[data-cy="templateActionButtons"] [data-icon="pencil"]',
  settingsTemplate: '[data-cy="templateActionButtons"] [data-icon="gear"]',
  confirmPublish: ".el-dialog > .el-dialog__footer > .dialog-footer > .el-button--primary",
  templateCard: (title) => `[data-cy="templateCard"] [title=${title}]`,
  templateWidth: '[placeholder="Width"]',
  templateHeight: '[placeholder="Height"]',
  colorFillPick: '[data-cy="fillFillPickerInputHex"]',
  sidebarItemTemplate: '[data-title="Templates"]',
  sidebarAnimation: '[data-cy="sideBarAnimations"]',
  breadcrumbTemplate: '[class="el-breadcrumb__inner"] [href="#/content/templates"]',
  introAnimation: '[data-cy="introSelectAnimation"]',
  rotateOption: '[data-cy="rotate-from-animation-option"]',
  introDuration: '[data-cy="introDurationInput"]',
  outroAnimation: '[data-cy="outroSelectAnimation"]',
  scaleOption: '[data-cy="scale-to-animation-option"]',
  outroDuration: '[data-cy="outroDurationInput"]',
  dragItem: '[data-cy="contentItem"]',
  canvas: '[data-cy="canvas"]',
};
